# -*- coding: utf-8 -*-
"""KNN_Using_scikit_learn

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j0im20iRonqT8KeAnYW_hjsauLm1n1Uy
"""

import pandas as pd

data = {
    "Distance_km": [2, 3, 4, 5, 7, 8, 10, 12, 15, 18],
    "Duration_min": [8, 12, 15, 18, 25, 30, 35, 40, 50, 60],
    "Category": [
        "Short",
        "Short",
        "Short",
        "Short",
        "Medium",
        "Medium",
        "Medium",
        "Medium",
        "Long",
        "Long"
    ]
}

df = pd.DataFrame(data)

print(df)

#Separate Features and Target
X = df[["Distance_km", "Duration_min"]]

y = df["Category"]

from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors=3)

model.fit(X, y)

new_ride = [[9, 32]]

prediction = model.predict(new_ride)

print("Predicted Ride Category:", prediction[0])

distance = float(
    input("Enter ride distance in km: "))

duration = float(
    input("Enter ride duration in minutes: "))

new_ride = [[distance, duration]]

prediction = model.predict(new_ride)

print("\n🚕 Ride Prediction")
print("------------------")
print("Distance:", distance, "km")
print("Duration:", duration, "minutes")
print("Predicted Category:", prediction[0])

#manhattan euclidean minkowski
model = KNeighborsClassifier(n_neighbors=3,metric="minkowski")

model.fit(X, y)

print(model.predict([[9, 32]]))